version: '3.7'
services:
  database:
    image: postgres
    container_name: rent_safe
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=db_rent_safe
      - POSTGRES_PASSWORD=Oficial1@3
      - POSTGRES_DB=rent_safe
    volumes:
      - pdgata:/data/postgres
    expose:
      - 5432
  api:
    build: .
    container_name: rent_safe_api
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/aluga-facil
      - /aluga-facil/node_modules
    links:
      - database
    depends_on:
      - database

volumes:
  pdgata:
    driver: local
